import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import Experience from "../components/experience";
import Skills from "../components/skills";
import Projects from "../components/projects";
import Contact from "../components/contact-me";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Prateek&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/p.svg" />
      </Head>

      <main className={styles.main}>

        <div>
          <div className={styles.card} id='experience'>
            <Experience/>
          </div>

          <div className={styles.card} id='skills'>
           <Skills/>
          </div>

          <div className={styles.card} id='projects'>
            <Projects/>
          </div>
          <div className={styles.card} id='contactme'>
            <Contact/>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
